version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    env_file: .env
    environment:
      PORT: ${PORT}
      MONGO_URL: ${MONGO_URL}
      TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET}
      COOKIE_KEY: ${COOKIE_KEY}
      CLIENT_HOME_PAGE_URL: ${CLIENT_HOME_PAGE_URL}
    ports:
      - '7000:7000'
    depends_on:
      - mongodb
    networks:
      - my-app
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      - my-app
    volumes:
      - mongo-data:/data/db
networks:
  my-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
