const REACT_APP_SERVER_PROD = process.env.REACT_APP_SERVER_PROD;
const REACT_APP_SERVER_DEV = process.env.REACT_APP_SERVER_DEV;
const REACT_APP_GA_ID = process.env.REACT_APP_GA_ID;

export { REACT_APP_SERVER_DEV, REACT_APP_SERVER_PROD, REACT_APP_GA_ID };
